# Generated by Django 3.1.3 on 2020-11-30 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20201129_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 7, 8, 11, 421199, tzinfo=utc)),
        ),
    ]
