# Generated by Django 3.1.3 on 2020-12-05 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_auto_20201201_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 11, 48, 3, 706820, tzinfo=utc)),
        ),
    ]
