# Generated by Django 3.1.3 on 2021-01-07 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20210107_1445'),
        ('accounts', '0022_user_reset'),
        ('archives', '0026_auto_20210103_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/$D/')),
                ('is_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 9, 15, 40, 763277, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='LecturePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.post')),
                ('lecture_start_date', models.DateTimeField(null=True)),
                ('lecture_end_date', models.DateTimeField(null=True)),
                ('post_details', models.ManyToManyField(blank=True, to='accounts.ProfileDetail')),
            ],
            bases=('home.post',),
        ),
    ]
