# Generated by Django 3.1.3 on 2020-11-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201120_1036'),
        ('accounts', '0003_auto_20201120_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.imageadd'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='details',
            field=models.ManyToManyField(blank=True, to='accounts.ProfileDetail'),
        ),
    ]
