# Generated by Django 3.1.3 on 2020-11-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201120_1037'),
        ('accounts', '0004_auto_20201120_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ManyToManyField(blank=True, to='home.ImageAdd'),
        ),
    ]
