# Generated by Django 3.1.3 on 2020-11-20 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201120_1235'),
        ('accounts', '0005_auto_20201120_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='links',
        ),
        migrations.AddField(
            model_name='contact',
            name='links',
            field=models.ManyToManyField(blank=True, to='home.PostLink'),
        ),
    ]
