# Generated by Django 3.1.3 on 2020-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201121_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='finalyear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
