# Generated by Django 3.1.3 on 2020-11-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_degree_finalyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.ManyToManyField(blank=True, to='accounts.Degree'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.personaldetail'),
        ),
    ]
