# Generated by Django 3.1.3 on 2020-11-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_personaldetail_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='position',
        ),
    ]
