# Generated by Django 3.1.3 on 2020-11-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201121_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='work',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
