# Generated by Django 3.1.3 on 2020-11-22 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20201122_1029'),
        ('accounts', '0015_personaldetail_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tag'),
        ),
    ]
