# Generated by Django 3.1.3 on 2020-11-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201122_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='work',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medicalcollege'),
        ),
    ]
