# Generated by Django 3.1.3 on 2020-11-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201123_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='cv/pdf/%Y/%m/$D/'),
        ),
    ]
