# Generated by Django 3.1.3 on 2020-11-20 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201120_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageadd',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 5, 34, 34, 79463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 5, 34, 34, 83226, tzinfo=utc)),
        ),
    ]
