# Generated by Django 3.1.3 on 2020-11-22 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20201121_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 19, 824464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 19, 826009, tzinfo=utc)),
        ),
    ]
