# Generated by Django 3.1.3 on 2020-12-01 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profiledetail_pdf'),
        ('home', '0041_auto_20201130_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='details',
            field=models.ManyToManyField(blank=True, to='accounts.ProfileDetail'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 16, 9, 7, 264263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 16, 9, 7, 265902, tzinfo=utc)),
        ),
    ]
