# Generated by Django 3.1.3 on 2020-12-05 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20201201_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 11, 48, 3, 649502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 11, 48, 3, 701353, tzinfo=utc)),
        ),
    ]
