# Generated by Django 3.1.3 on 2020-12-05 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20201205_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 13, 21, 21, 265827, tzinfo=utc)),
        ),
    ]
