# Generated by Django 3.1.3 on 2020-12-24 01:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20201224_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 20, 12, 51, 320346, tzinfo=utc)),
        ),
    ]
