# Generated by Django 3.1.3 on 2021-01-03 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20210103_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 14, 51, 23, 636658, tzinfo=utc)),
        ),
    ]
