# Generated by Django 3.1.3 on 2021-01-10 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20210108_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 11, 29, 19, 233941, tzinfo=utc)),
        ),
    ]
