# Generated by Django 3.1.3 on 2021-01-12 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_auto_20210112_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 15, 21, 2, 666120, tzinfo=utc)),
        ),
    ]
