# Generated by Django 3.1.3 on 2021-01-23 01:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20210112_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 20, 28, 16, 943901, tzinfo=utc)),
        ),
    ]
