# Generated by Django 3.1.3 on 2021-01-30 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_auto_20210128_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 5, 21, 3, 258661, tzinfo=utc)),
        ),
    ]
