# Generated by Django 3.1.3 on 2020-12-12 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0050_auto_20201212_1150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.BooleanField(default=False)),
                ('degree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('question', models.CharField(blank=True, max_length=1000000, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000000, null=True)),
                ('mcq', models.BooleanField(default=False)),
                ('flashcard', models.BooleanField(default=False)),
                ('qa', models.BooleanField(default=False)),
                ('links', models.ManyToManyField(blank=True, to='home.PostLink')),
                ('tag', models.ManyToManyField(null=True, to='home.Tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Questionbank/')),
                ('aimage', models.BooleanField(default=False)),
                ('qimage', models.BooleanField(default=False)),
                ('qinstance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcq.questionbank')),
            ],
        ),
    ]
