# Generated by Django 3.1.3 on 2020-11-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201120_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='backgroundImage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profilePic',
        ),
    ]
