# Generated by Django 3.1.3 on 2020-11-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201121_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
