# Generated by Django 3.1.3 on 2020-11-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201122_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='degree',
        ),
    ]
