# Generated by Django 3.1.3 on 2020-11-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20201123_1228'),
        ('accounts', '0018_remove_personaldetail_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='work',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicalcollege',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='profiledetail',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.ManyToManyField(blank=True, to='home.PostLink'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='degree',
            name='college',
        ),
        migrations.AddField(
            model_name='degree',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medicalcollege'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='PersonalDetail',
        ),
        migrations.AddField(
            model_name='work',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medicalcollege'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work',
            field=models.ManyToManyField(blank=True, to='accounts.Work'),
        ),
    ]
