# Generated by Django 3.1.3 on 2020-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profiledetail_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='backgroundpic',
            field=models.ImageField(blank=True, null=True, upload_to='backgroundpic/%Y/%m/$D/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/%Y/%m/$D/'),
        ),
    ]
