# Generated by Django 3.1.3 on 2020-12-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201205_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
