# Generated by Django 3.1.3 on 2021-01-12 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestobj',
            old_name='headers',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='requestobj',
            name='ip',
        ),
        migrations.AddField(
            model_name='requestobj',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 14, 22, 0, 283579, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='requestobj',
            name='page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
