# Generated by Django 3.1.3 on 2021-01-23 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20210112_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageobj',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestobj',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 23)),
        ),
    ]
