# Generated by Django 3.1.3 on 2021-01-30 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20210128_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestobj',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 30)),
        ),
    ]
