# Generated by Django 3.1.3 on 2020-11-18 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201116_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_speciality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 2, 2, 39, 602880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 2, 2, 39, 603762, tzinfo=utc)),
        ),
    ]
