# Generated by Django 3.1.3 on 2020-11-18 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201119_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img1',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 21, 18, 5, 389439, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, to='home.ImageAdd'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 21, 18, 5, 391590, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, to='home.ImageAdd'),
        ),
    ]
