# Generated by Django 3.1.3 on 2020-11-29 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20201124_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='link_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 17, 5, 33, 950522, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='commentimages/%Y/%m/$D/'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='link',
        ),
        migrations.AddField(
            model_name='comment',
            name='link',
            field=models.ManyToManyField(blank=True, null=True, to='home.PostLink'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 17, 5, 33, 952319, tzinfo=utc)),
        ),
    ]
