# Generated by Django 3.1.3 on 2020-12-12 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20201206_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 6, 8, 1, 254152, tzinfo=utc)),
        ),
    ]
