# Generated by Django 3.1.3 on 2021-01-03 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20210103_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 16, 20, 54, 973712, tzinfo=utc)),
        ),
    ]
