# Generated by Django 3.1.3 on 2021-01-07 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20210103_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 9, 15, 40, 692988, tzinfo=utc)),
        ),
    ]
