# Generated by Django 3.1.3 on 2021-01-08 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20210107_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lecture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 7, 53, 30, 93404, tzinfo=utc)),
        ),
    ]
