# Generated by Django 3.1.3 on 2020-11-29 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20201129_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 17, 25, 23, 379404, tzinfo=utc)),
        ),
    ]
