# Generated by Django 3.1.3 on 2020-11-30 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_auto_20201130_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 7, 19, 1, 350542, tzinfo=utc)),
        ),
    ]
