# Generated by Django 3.1.3 on 2020-12-01 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20201130_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 16, 9, 7, 270807, tzinfo=utc)),
        ),
    ]
