# Generated by Django 3.1.3 on 2020-12-12 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0013_auto_20201212_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 6, 20, 43, 639850, tzinfo=utc)),
        ),
    ]
