# Generated by Django 3.1.3 on 2020-12-24 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0016_auto_20201224_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 20, 8, 5, 735319, tzinfo=utc)),
        ),
    ]
